name: 'Include the VCN CLI in your workflow'
description: 'Use the VCN tool from CodeNotary.com to notarize and authenticate digital assets and generate a Bill of materials for supported project types'
branding:
  icon: 'lock'
  color: 'green'
inputs:
  version:
    description: 'Override latest with a specific vcn version'
    required: false
  asset:
    description: 'Asset to notarize/authenticate.'
    required: false
  mode:
    description: 'Whether to notarize or authenticate (use only "n" for notarize and "a" for authenticate")'
    default: n
    required: false
  cnil_host:
    description: 'CodeNotary Immutable Ledger (CNIL) host.'
    required: true
  cnil_grpc_port:
    description: 'CNIL gRPC port.'
    required: false
    default: 443
  cnil_api_key:
    description: 'CNIL API key.'
    required: false
  standard_usage:
    description: 'False if you will NOT use the inputs but rather configure your own environment variables/and commands.'
    default: true
    required: true
runs:
  using: 'composite'
  steps:
      - run: chmod +x ${{github.action_path}}/get-vcn.sh && bash ${{github.action_path}}/get-vcn.sh ${{ inputs.version }}
        shell: bash
      - run: test "${{inputs.standard_usage}}" = "true" && { ./vcn login --lc-host ${{ inputs.cnil_host }} --lc-port ${{ inputs.cnil_grpc_port }} --lc-api-key ${{ inputs.cnil_api_key }} && ./vcn ${{inputs.mode}} ${{ inputs.asset }} ; }  || exit 0
        shell: bash
