name: 'VCN generate and notarize BoM for Go projects'
description: 'Uses the VCN tool from CodeNotary.com to generate and notarize the bill of materials (BoM) for Go projects and binaries.'
branding:
  icon: 'lock'
  color: 'green'
inputs:
  version:
    description: 'Override latest with a specific vcn version'
    required: false
runs:
  using: 'composite'
  steps:
      - run: chmod +x ${{github.action_path}}/get-vcn.sh && bash ${{github.action_path}}/get-vcn.sh
        shell: bash
