name: 'Include the VCN CLI in your workflow'
description: 'Use the VCN tool from CodeNotary.com to notarize and authenticate digital assets and generate a Bill of materials for supported project types'
branding:
  icon: 'lock'
  color: 'green'
inputs:
  version:
    description: 'Override latest with a specific vcn version'
    required: false
runs:
  using: 'composite'
  steps:
      - run: chmod +x ${{github.action_path}}/get-vcn.sh && bash -x ${{github.action_path}}/get-vcn.sh ${{ inputs.version }}
        shell: bash
