name: get-vcn

on:
  push:
    branches: [main]

jobs:
  get-latest-vcn-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.review.commit_id }}

      - name: Download VCN
        uses: codenotary/vcn-github-action@main          

      - name: Test vcn binary is available
        run: ./vcn --help; ./vcn a ./vcn
        shell: bash

  get-some-other-version-vcn-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Download VCN
        uses: codenotary/vcn-github-action@main
        with:
            version: v0.9.8
            asset: vcn   
      - name: Test vcn binary is available
        run: ./vcn --help; ./vcn a ./vcn
        shell: bash

